version: 0.2

phases:
  install:
    java: corretto11
    docker: 19
    build:
      commands:
        - echo Build started on `date`
        - mvn clean package
artifacts:
  filters:
    - '**/*'
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
