openapi: '3.0.0'
info:
  version: '1.0.0'
  title: realmeet
servers:
  - url: 'http://localhost:3000'

paths:
  /rooms:
    get:
      summary: 'Returns rooms'
      operationId: listRooms
      tags:
        - room
      parameters:
        - name: id
          in: query
          description: Id of the room
          schema:
            type: integer
            format: int64

      responses:

        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

components:
  schemas:
    Room:
      type: object

      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
