#=======================
#  Server
#=======================
server:
  port: 8080
  servlet:
    context-path: /v1

#=======================
#  Spring Boot
#=======================
spring:
  profiles:
    active: dev
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql://localhost:3306/bluemeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ander22
    type: com.zaxxer.hikari.HikariDataSource

#=======================
#  Logging
#=======================
logging:
  level:
    org.springframework: INFO
    org.flyway db: INFO