#=======================
#  Spring
#=======================
spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql:containers-us-west-189.railway.app:5899/railway?&serverTimezone=UTC&useSSL=false
    username: root
